# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.created.com:
    container_name: orderer.created.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../../artifacts/channel/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../../artifacts/channel/crypto-config/ordererOrganizations/created.com/orderers/orderer.created.com/msp:/var/hyperledger/orderer/msp
    - ../../artifacts/channel/crypto-config/ordererOrganizations/created.com/orderers/orderer.created.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.leftorg1.created.com:
    container_name: peer0.leftorg1.created.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.leftorg1.created.com
      - CORE_PEER_ADDRESS=peer0.leftorg1.created.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.leftorg1.created.com:7051
      - CORE_PEER_LOCALMSPID=LeftOrg1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../artifacts/channel/crypto-config/peerOrganizations/leftorg1.created.com/peers/peer0.leftorg1.created.com/msp:/etc/hyperledger/fabric/msp
        - ../../artifacts/channel/crypto-config/peerOrganizations/leftorg1.created.com/peers/peer0.leftorg1.created.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer1.leftorg1.created.com:
    container_name: peer1.leftorg1.created.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.leftorg1.created.com
      - CORE_PEER_ADDRESS=peer1.leftorg1.created.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.leftorg1.created.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.leftorg1.created.com:7051
      - CORE_PEER_LOCALMSPID=LeftOrg1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../artifacts/channel/crypto-config/peerOrganizations/leftorg1.created.com/peers/peer1.leftorg1.created.com/msp:/etc/hyperledger/fabric/msp
        - ../../artifacts/channel/crypto-config/peerOrganizations/leftorg1.created.com/peers/peer1.leftorg1.created.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:7051
      - 8053:7053

  peer0.rightorg2.created.com:
    container_name: peer0.rightorg2.created.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.rightorg2.created.com
      - CORE_PEER_ADDRESS=peer0.rightorg2.created.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.rightorg2.created.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.rightorg2.created.com:7051
      - CORE_PEER_LOCALMSPID=RightOrg2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../artifacts/channel/crypto-config/peerOrganizations/rightorg2.created.com/peers/peer0.rightorg2.created.com/msp:/etc/hyperledger/fabric/msp
        - ../../artifacts/channel/crypto-config/peerOrganizations/rightorg2.created.com/peers/peer0.rightorg2.created.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer1.rightorg2.created.com:
    container_name: peer1.rightorg2.created.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.rightorg2.created.com
      - CORE_PEER_ADDRESS=peer1.rightorg2.created.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.rightorg2.created.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.rightorg2.created.com:7051
      - CORE_PEER_LOCALMSPID=RightOrg2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../artifacts/channel/crypto-config/peerOrganizations/rightorg2.created.com/peers/peer1.rightorg2.created.com/msp:/etc/hyperledger/fabric/msp
        - ../../artifacts/channel/crypto-config/peerOrganizations/rightorg2.created.com/peers/peer1.rightorg2.created.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
