# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  orderer.created.com:
    extends:
      file:   ../base/docker-compose-base.yaml
      service: orderer.created.com
    container_name: orderer.created.com
    networks:
      - byfn

  peer0.leftorg1.created.com:
    container_name: peer0.leftorg1.created.com
    extends:
      file:  ../base/docker-compose-base.yaml
      service: peer0.leftorg1.created.com
    networks:
      - byfn

  peer1.leftorg1.created.com:
    container_name: peer1.leftorg1.created.com
    extends:
      file:  ../base/docker-compose-base.yaml
      service: peer1.leftorg1.created.com
    networks:
      - byfn

  peer0.rightorg2.created.com:
    container_name: peer0.rightorg2.created.com
    extends:
      file:  ../base/docker-compose-base.yaml
      service: peer0.rightorg2.created.com
    networks:
      - byfn

  peer1.rightorg2.created.com:
    container_name: peer1.rightorg2.created.com
    extends:
      file:  ../base/docker-compose-base.yaml
      service: peer1.rightorg2.created.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.leftorg1.created.com:7051
      - CORE_PEER_LOCALMSPID=LeftOrg1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/leftorg1.created.com/peers/peer0.leftorg1.created.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/leftorg1.created.com/peers/peer0.leftorg1.created.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/leftorg1.created.com/peers/peer0.leftorg1.created.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/leftorg1.created.com/users/Admin@leftorg1.created.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT; '
    volumes:
        - /var/run/:/host/var/run/
        - ../../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ../../artifacts/channel/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ../../artifacts/channel/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.created.com
      - peer0.leftorg1.created.com
      - peer1.leftorg1.created.com
      - peer0.rightorg2.created.com
      - peer1.rightorg2.created.com
    networks:
      - byfn

